import React, { useState, useEffect } from 'react';
import { Globe } from 'lucide-react';

const DeadInternetKnowledge = () => {
  const [loading, setLoading] = useState(true);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setProgress(prev => (prev < 100 ? prev + 1 : 100));
    }, 50);

    setTimeout(() => {
      setLoading(false);
    }, 5000);

    return () => clearInterval(timer);
  }, []);

  return (
    <div className="max-w-4xl mx-auto p-6 bg-black text-green-400 font-mono">
      <div className="border border-green-500 p-4 mb-6">
        <div className="flex items-center gap-2 mb-4">
          <Globe size={24} />
          <span className="text-lg">AI TRAINING MODULE: DEAD INTERNET THEORY</span>
        </div>
        {loading ? (
          <div className="space-y-2">
            <div className="flex justify-between">
              <span>Initializing internet authenticity analysis...</span>
              <span>{progress}%</span>
            </div>
            <div className="w-full bg-gray-900 rounded">
              <div 
                className="h-2 bg-green-500 rounded transition-all duration-500"
                style={{ width: `${progress}%` }}
              ></div>
            </div>
          </div>
        ) : null}
      </div>

      <div className="space-y-6">
        <div className="border border-green-500 p-4">
          <div className="text-green-300 mb-2">[SECTION_01: GENERAL_INFORMATION]</div>
          <div className="opacity-80">
            <span className="text-yellow-400">{">>>"}</span> Processing theory overview...
            <pre className="whitespace-pre-wrap text-sm mt-2">
              The Dead Internet Theory suggests that the majority of internet content 
              and interactions are artificially generated by automated systems and 
              AI rather than real humans. This theory emerged from observations about 
              increasing content automation, repetitive patterns in social media, 
              and the prevalence of bot activities across digital platforms.
            </pre>
          </div>
        </div>

        <div className="border border-green-500 p-4">
          <div className="text-green-300 mb-2">[SECTION_02: TECHNICAL_PARAMETERS]</div>
          <div className="opacity-80">
            <span className="text-yellow-400">{">>>"}</span> Processing automation metrics...
            <pre className="whitespace-pre-wrap text-sm mt-2">
              CONTENT_GENERATION: {
                `{
                  bots: "automated_posting_systems",
                  ai_content: "language_models_output",
                  algorithmic_curation: "content_recommendation_systems"
                }`
              }
              
              TRAFFIC_ANALYSIS: {
                `{
                  bot_percentage: "estimated_40_to_60_percent",
                  engagement_metrics: "likes_shares_comments",
                  authentication_methods: "captcha_behavioral_analysis"
                }`
              }
              
              AUTOMATION_INDICATORS: {
                `{
                  pattern_recognition: "repeated_phrases",
                  timing_analysis: "posting_intervals",
                  interaction_authenticity: "response_patterns"
                }`
              }
            </pre>
          </div>
        </div>

        <div className="border border-green-500 p-4">
          <div className="text-green-300 mb-2">[SECTION_03: EXPERT_DATABASE]</div>
          <div className="opacity-80">
            <span className="text-yellow-400">{">>>"}</span> Loading researcher profiles...
            <pre className="whitespace-pre-wrap text-sm mt-2">
              EXPERT_01: {
                `{
                  name: "Dr. Filippo Menczer",
                  specialty: "bot_network_analysis",
                  status: "active",
                  research: "social_media_manipulation"
                }`
              }
              
              EXPERT_02: {
                `{
                  name: "Dr. Kate Starbird",
                  specialty: "disinformation_networks",
                  status: "active",
                  focus: "online_information_ecosystems"
                }`
              }
              
              EXPERT_03: {
                `{
                  name: "Dr. Jonathan Zittrain",
                  specialty: "internet_futures",
                  status: "active",
                  contribution: "digital_authentication_research"
                }`
              }
            </pre>
          </div>
        </div>

        <div className="border border-green-500 p-4">
          <div className="text-green-300 mb-2">[SECTION_04: RECENT_DISCOVERIES]</div>
          <div className="opacity-80">
            <span className="text-yellow-400">{">>>"}</span> Processing research findings...
            <pre className="whitespace-pre-wrap text-sm mt-2">
              DISCOVERY_LOG: {
                `{
                  "AI_Detection": "advanced_content_generation_markers",
                  "Bot_Networks": "sophisticated_behavior_patterns",
                  "Traffic_Analysis": "automated_engagement_systems",
                  "Authentication": "new_human_verification_methods"
                }`
              }
            </pre>
          </div>
        </div>

        <div className="border border-green-500 p-4">
          <div className="text-green-300 mb-2">[SECTION_05: CONSPIRACY_ANALYSIS]</div>
          <div className="opacity-80">
            <span className="text-yellow-400">{">>>"}</span> Loading theory components...
            <pre className="whitespace-pre-wrap text-sm mt-2">
              THEORY_NAME: "Dead_Internet_Theory"
              CLASSIFICATION: "emerging_digital_phenomenon"
              MAIN_CLAIMS: {
                `{
                  "claim_1": "majority_content_AI_generated",
                  "claim_2": "controlled_information_flow",
                  "claim_3": "simulated_social_interactions"
                }`
              }
            </pre>
          </div>
        </div>

        <div className="border border-green-500 p-4">
          <div className="text-green-300 mb-2">[SECTION_06: BRANCHING_TOPICS]</div>
          <div className="opacity-80">
            <span className="text-yellow-400">{">>>"}</span> Analyzing related fields...
            <pre className="whitespace-pre-wrap text-sm mt-2">
              BRANCH_01: {
                `{
                  field: "Digital_Authentication",
                  focus: "human_verification_systems"
                }`
              }
              
              BRANCH_02: {
                `{
                  field: "AI_Content_Detection",
                  focus: "automated_content_identification"
                }`
              }
              
              BRANCH_03: {
                `{
                  field: "Social_Media_Psychology",
                  focus: "online_interaction_authenticity"
                }`
              }
            </pre>
          </div>
        </div>
      </div>

      <div className="mt-6 border-t border-green-500 pt-4 text-sm opacity-80">
        <span className="text-yellow-400">{">>>"}</span> Internet analysis complete
        <br />
        <span className="text-yellow-400">{">>>"}</span> Neural network ready for authenticity verification
      </div>
    </div>
  );
};

export default DeadInternetKnowledge;